name: "git release"

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # List Node exeuction versions
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org/"
      - run: "npm ci"
      - run: "npm run build --if-present"
      - run: "npm test"
      - run: "npx semantic-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}


  # git-release:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # List node versions to run tests with
  #       node-version: [12.x]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: "Setup Node.js"
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: "Install dependencies"
  #       run: "npm ci"
  #     - name: "Release"
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: "npx semantic-release"
